#!/usr/bin/awk -f

# The arguments are: lat1 lng1 X1 X2 X3 lat2 lng2 X4...
# This format is due to how 'find_products.sh' works
# The output will be: distance X1 X2 X3 lat2 lng2 X4...

{
PI=3.14159265359
R=6372800 # Radius of earth, in km;

dlat = ($6-$1)*PI/180;
dlng = ($7-$2)*PI/180;
lat1 = ($1)*PI/180;
lat2 = ($6)*PI/180;

a = sin(dlat/2)**2 + cos(lat1)*cos(lat2)*(sin(dlng/2)**2);

# asin(x) = 2*(atan(x / (1 + sqrt(1 - x**2))))
x = sqrt(a)
c = 2*(2*atan2(x, 1 + sqrt(1 - x**2)))
distance = R*c

printf "%f ", distance
print $0
}
